name: CI Pipeline

# Eventos que activan el pipeline
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:

  job1:
    runs-on: ubuntu-latest  

    steps:
      # 1. Clonar el código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ejecutar pruebas
      - name: Run tests
        run: pytest tests/

  job2:
    sonarqube:
    name: SonarQube
    needs: job1
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
