name: CI Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  job1:
    runs-on: ubuntu-latest  

    steps:
      # 1. Clonar el c칩digo fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ejecutar pruebas
      - name: Run tests
        run: pytest tests/

  sonarqube:
    needs: job1
    runs-on: ubuntu-latest  # Cambiado a ubuntu para mayor compatibilidad con SonarQube

    steps:
      # 1. Clonar el repositorio con todo el historial
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Clonado completo para an치lisis relevante

      # 2. Escaneo de SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de GitHub para informaci칩n de PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token de autenticaci칩n para SonarQube
